file(READ "${DRIVER_SOURCE_DIR}/item-tooltip-cache.lua" cache_source)
file(READ "${DRIVER_SOURCE_DIR}/boot.lua" boot_source)
file(READ "${DRIVER_SOURCE_DIR}/mobile-policy.lua" mobile_source)
set(boot_source "local installMobilePolicy = (function()\n${mobile_source}\nend)()\n${boot_source}")
file(READ "${DRIVER_SOURCE_DIR}/gc-policy.lua" gc_source)
set(boot_source "local installRuntimeGC = (function()\n${gc_source}\nend)()\ninstallRuntimeGC('ui', GetRuntimeGCPause())\n${boot_source}")
file(READ "${DRIVER_SOURCE_DIR}/unique-sort-workers.lua" unique_workers_source)
set(boot_source "local installUniqueSortWorkers = (function()\n${unique_workers_source}\nend)()\n${boot_source}")
file(READ "${DRIVER_SOURCE_DIR}/helper-boot.lua" helper_source)
file(WRITE "${CMAKE_BINARY_DIR}/helper-boot.lua" "local installRuntimeGC = (function()\n${gc_source}\nend)()\ninstallRuntimeGC('helper', GetRuntimeGCPause())\n${helper_source}")
file(READ "${CMAKE_BINARY_DIR}/helper-boot.lua" helper_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" helper_c ${helper_hex})
file(WRITE "${CMAKE_BINARY_DIR}/helper_boot.c" "const char* helper_boot_lua = \"${helper_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/runtime-profile.lua" profile_source)
file(READ "${DRIVER_SOURCE_DIR}/calculation-scheduler.lua" scheduler_source)
file(READ "${DRIVER_SOURCE_DIR}/unique-comparison-delay.lua" unique_delay_source)
file(WRITE "${CMAKE_BINARY_DIR}/boot.lua" "local installItemTooltipCache = (function()\n${cache_source}\nend)()\nlocal installRuntimeProfile = (function()\n${profile_source}\nend)()\nlocal calculationScheduler = (function()\n${scheduler_source}\nend)()\nlocal installUniqueComparisonDelay = (function()\n${unique_delay_source}\nend)()\n${boot_source}")
file(READ "${CMAKE_BINARY_DIR}/boot.lua" file_content HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" c_string ${file_content})
file(WRITE ${CMAKE_BINARY_DIR}/boot.c "const char* boot_lua = \"${c_string}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/item-tooltip-cache.lua" cache_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" cache_c ${cache_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/item-tooltip-cache.lua" test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" test_c ${test_hex})
file(WRITE "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* cache_lua = \"${cache_c}\";\nconst char* cache_test_lua = \"${test_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/gc-policy.lua" gc_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" gc_c ${gc_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/gc-policy.lua" gc_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" gc_test_c ${gc_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* gc_policy_lua = \"${gc_c}\";\nconst char* gc_policy_test_lua = \"${gc_test_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/runtime-profile.lua" profile_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" profile_c ${profile_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/runtime-profile.lua" profile_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" profile_test_c ${profile_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* runtime_profile_lua = \"${profile_c}\";\nconst char* runtime_profile_test_lua = \"${profile_test_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/calculation-scheduler.lua" scheduler_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" scheduler_c ${scheduler_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/calculation-scheduler.lua" scheduler_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" scheduler_test_c ${scheduler_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* calculation_scheduler_lua = \"${scheduler_c}\";\nconst char* calculation_scheduler_test_lua = \"${scheduler_test_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/../packer/src/timeless-seeds.lua" seeds_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" seeds_c ${seeds_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/timeless-seeds.lua" seeds_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" seeds_test_c ${seeds_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* timeless_seeds_lua = \"${seeds_c}\";\nconst char* timeless_seeds_test_lua = \"${seeds_test_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/../packer/src/timeless-inflate.lua" inflate_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" inflate_c ${inflate_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/timeless-inflate.lua" inflate_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" inflate_test_c ${inflate_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* timeless_inflate_lua = \"${inflate_c}\";\nconst char* timeless_inflate_test_lua = \"${inflate_test_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/unique-comparison-delay.lua" unique_delay_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" unique_delay_c ${unique_delay_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/unique-comparison-delay.lua" unique_delay_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" unique_delay_test_c ${unique_delay_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* unique_delay_lua = \"${unique_delay_c}\";\nconst char* unique_delay_test_lua = \"${unique_delay_test_c}\";\n")
file(READ "${DRIVER_SOURCE_DIR}/unique-sort-workers.lua" unique_workers_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" unique_workers_c ${unique_workers_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/unique-sort-workers.lua" unique_workers_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" unique_workers_test_c ${unique_workers_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* unique_workers_lua = \"${unique_workers_c}\";\nconst char* unique_workers_test_lua = \"${unique_workers_test_c}\";\n")

file(READ "${DRIVER_SOURCE_DIR}/mobile-policy.lua" mobile_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" mobile_c ${mobile_hex})
file(READ "${DRIVER_SOURCE_DIR}/test/lua/mobile-policy.lua" mobile_test_hex HEX)
string(REGEX REPLACE "(..)" "\\\\x\\1" mobile_test_c ${mobile_test_hex})
file(APPEND "${CMAKE_BINARY_DIR}/item_tooltip_cache_test.c" "const char* mobile_policy_lua = \"${mobile_c}\";\nconst char* mobile_policy_test_lua = \"${mobile_test_c}\";\n")
